// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parus.Infrastructure.DLA;

#nullable disable

namespace Parus.Infrastructure.Migrations.BillingDb
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20240322171349_Init1")]
    partial class Init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parus.Core.Entities.SubscribeProfile", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Key");

                    b.ToTable("SubscribeProfiles");
                });

            modelBuilder.Entity("Parus.Core.Entities.SubscribeSession", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Key"));

                    b.Property<int>("ExpiresAt")
                        .HasColumnType("int");

                    b.Property<int?>("ProfileKey")
                        .HasColumnType("int");

                    b.Property<string>("PurchaserUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubjectUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("ProfileKey");

                    b.ToTable("SubscribeSessions");
                });

            modelBuilder.Entity("Parus.Core.Entities.SubscribeSession", b =>
                {
                    b.HasOne("Parus.Core.Entities.SubscribeProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileKey");

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
