#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 80
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["Parus.API/Parus.API.csproj", "Parus.API/"]
COPY ["Parus.Common/Parus.Common.csproj", "Parus.Common/"]
COPY ["Parus.Core/Parus.Core.csproj", "Parus.Core/"]
COPY ["Parus.Infrastructure/Parus.Infrastructure.csproj", "Parus.Infrastructure/"]
RUN dotnet restore "./Parus.API/./Parus.API.csproj"
COPY . .
WORKDIR "/src/Parus.API"
RUN dotnet build "./Parus.API.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./Parus.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Parus.API.dll"]